opengisproj/opengisproj/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic import RedirectView

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^portal/', include('portal.urls', namespace='portal')),
    url(r'^account/', include('accounts.urls', namespace='accounts')),
    url(r'', RedirectView.as_view(url="/portal/home/", permanent=True)),
]

opengisproj/portal/urls.py
from django.conf.urls import url
from django.views.generic import RedirectView

from . import views

urlpatterns = [
    url(r'^home/?$', views.home, name='home'),
    url(r'^add/?$', views.add, name='add-data'),
    url(r'^browse/?$', views.browse, name='browse-data'),
    url(r'^parameters/?$', views.addParam, name='parameters'),
    url(r'^datagroups/?$', views.dataGroups, name='datagroups'),
    url(r'^reports/?$', views.reports, name='reports'),
    url(r'^shapefiles/?$', views.shapefilesManager, name='shapefiles'),
    url(r'^importer/?$', views.importView, name='importer'),
    url(r'^ajax/(?P<action>[a-zA-Z]*)/?$', views.processAjax, name='ajax'),
    url(r'^fileupload/?$', views.fileupload, name='upload-manager'),
    url(r'^/?$', RedirectView.as_view(url='/portal/home')),
    url(r'', views.pageNotFound, name='404')
]

opengisproj/portal/models.py
from django.db import models
from django.contrib.auth.models import User
from datetime import datetime

# Create your models here.

class data_groups(models.Model):
    name = models.CharField(max_length=100)
    is_removable = models.BooleanField(default=True)
    class Meta:
        db_table = "data_groups"

class gis_data(models.Model):
    created_on = models.DateTimeField(default=datetime.now)
    created_by = models.ForeignKey(User)
    data_group = models.ForeignKey(data_groups)

    class Meta:
        db_table = "gis_data"

class gis_data_meta(models.Model):
    key = models.CharField(max_length=100)
    value = models.TextField()
    data = models.ForeignKey(gis_data,on_delete=models.CASCADE)   

    class Meta:
        db_table = "gis_data_meta"

class options(models.Model):
    option_name = models.CharField(max_length=100)
    value = models.TextField()
    is_removable = models.BooleanField(default=False)
    data_group = models.ForeignKey(data_groups, null=True)

    class Meta:
        db_table = "options"

class uploads(models.Model):
    file_name = models.CharField(max_length=256)
    description = models.TextField(blank=True)
    file_ref = models.FileField(upload_to='uploads/%Y/%m/%d')
    uploaded_at = models.DateTimeField(auto_now_add=True)
    file_meta = models.CharField(max_length=150)
    class Meta:
        db_table = "uploads"

class shapefiles(models.Model):
    shape_name = models.CharField(max_length=256)
    shp_file = models.ForeignKey(uploads, related_name='shp_file', on_delete=models.CASCADE)
    dbf_file = models.ForeignKey(uploads, related_name='dbf_file', on_delete=models.CASCADE)
    shx_file = models.ForeignKey(uploads, related_name='shx_file',on_delete=models.CASCADE)

    class Meta:
        db_table = "shapefiles"

opengisproj/portal/forms.py
from django import forms
from .models import uploads


class UploadForm(forms.ModelForm):
    class Meta:
        model = uploads
        fields = ('file_name', 'description', 'file_ref', 'file_meta')
        labels = {
            'file_name': "Enter File Name",
            'description': "Enter description",
            'file_ref': "Select a file",
            'file_meta': "Upload Type",
        }
        widgets = {
            'file_name': forms.TextInput(attrs={'class': 'form-control',  'required': True}),
            'description': forms.TextInput(attrs={'class': 'form-control'}),
            'file_ref': forms.FileInput(attrs={'class': 'form-control', 'required': True}),
            'file_meta': forms.TextInput(attrs={'class': 'form-control', 'required': True}),
        }

opengisproj/portal/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse, JsonResponse
from .utils import *
from .forms import UploadForm
# Create your views here.


def home(request):
    if request.user.is_authenticated == False:
        return redirect('/portal/reports')
    elif request.user.is_staff == True:
        f = get_meta_fields()
        return render(request, 'portal/index.html', {'meta_fields': f})


def add(request):
    if request.user.is_authenticated == False:
        return redirect('/account/login?next=/portal/add')
    f = get_meta_fields()
    return render(request, 'portal/add-new.html', {'meta_fields': f})


def browse(request):
    if request.user.is_authenticated == False:
        return redirect('/account/login?next=/portal/browse')
    return render(request, 'portal/browse.html')


def addParam(request):
    if request.user.is_authenticated == False:
        return redirect('/account/login?next=/portal/parameters')
    return render(request, 'portal/add-param.html')


def dataGroups(request):
    if request.user.is_authenticated == False:
        return redirect('/account/login?next=/portal/datagroups')
    return render(request, 'portal/data-groups.html')


def reports(request):
    return render(request, 'portal/reports.html')


def shapefilesManager(request):
    if request.user.is_authenticated == False:
        return redirect('/accounts/login?next=/portal/shapefiles')
    form = UploadForm()
    return render(request, 'portal/shapefiles.html', {'form': form, 'meta': 'shapefile'})


def fileupload(request):
    if request.user.is_authenticated == False:
        return redirect('/accounts/login?next=/portal/shapefiles')
    if request.method == 'POST':
        form = UploadForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            form = UploadForm()
            return render(request, 'portal/upload.html', {'msg': "Successfully Uploaded!", 'form': form})
    else:
        form = UploadForm()
        return render(request, 'portal/upload.html', {'form': form})


def importView(request):
    if request.user.is_authenticated == False:
        return redirect('/account/login?next=/portal/importView')
    form = UploadForm()
    return render(request, 'portal/importView.html', {'form': form})


def processAjax(request, action):
    action_ignore_auth = ['getmetafields', 'getgisdata',
                          'getdatagroups', 'getshapes', 'getshapefilecoord']
    if request.user.is_authenticated == False and action not in action_ignore_auth:
        return JsonResponse("Unauthenticated Request", safe=False)
    if action == 'getmetafields':
        res = get_meta_fields()
        return JsonResponse(res, safe=False, content_type="text/html")
    elif action == "addNewData":
        if request.method == "POST":
            post_data = request.POST
            res = add_new_data(post_data, request.user, ret_json=True)
            return JsonResponse(res, safe=False)
        else:
            return JsonResponse("Form Data Missing or Invalid Request", safe=False)
    elif action == "getgisdata":
        if(request.method == "GET"):
            get_data = request.GET
            res = get_meta()
            return JsonResponse(res, safe=False)
        else:
            return JsonResponse("Form Data Missing or Invalid Request", safe=False)
    elif action == "addnewparam":
        if(request.method == "POST"):
            post_data = request.POST
            res = add_param(post_data, user=request.user)
            return JsonResponse(res, safe=False)
        else:
            return JsonResponse("Form Data Missing or Invalid Request", safe=False)
    elif action == "removeparam":
        if(request.method == "POST"):
            post_data = request.POST
            res = remove_param(
                option_id=post_data['id'], group_id=post_data['data_group'], user=request.user)
            return JsonResponse(res, safe=False)
        else:
            return JsonResponse("Form Data Missing or Invalid Request", safe=False)
    elif action == "importgisdata":
        if(request.method == "POST"):
            post_data = request.POST
            res = import_gis_data(post_data['file_id'])
            return JsonResponse(res, safe=False, content_type="text/html")
        else:
            return JsonResponse("Form Data Missing or Invalid Request", safe=False)
    elif action == "getexceldatafrommapping":
        if(request.method == "POST"):
            post_data = request.POST
            res = get_excel_data_from_mapping(
                post_data['mapping'], post_data['file_id'], post_data['data_group'])
            return JsonResponse(res, safe=False, content_type="text/html")
        else:
            return JsonResponse("Form Data Missing or Invalid Request", safe=False)
    elif action == "removedata":
        if(request.method == "POST"):
            post_data = request.POST
            res = remove_gis_data(data_id=post_data['id'], user=request.user)
            return JsonResponse(res, safe=False)
        else:
            return JsonResponse("Form Data Missing or Invalid Request", safe=False)
    elif action == "editdata":
        if(request.method == "POST"):
            post_data = request.POST
            res = edit_gis_data(
                meta_key=post_data['key'], data_id=post_data['dataId'], new_value=post_data['value'], user=request.user)
            return JsonResponse(res, safe=False)
        else:
            return JsonResponse("Form Data Missing or Invalid Request", safe=False)
    elif action == "editparam":
        if(request.method == "POST"):
            post_data = request.POST
            res = edit_gis_param(
                param_key=post_data['key'], opt_id=post_data['paramId'], new_value=post_data['value'], user=request.user)
            return JsonResponse(res, safe=False)
        else:
            return JsonResponse("Form Data Missing or Invalid Request", safe=False)
    elif action == "getdatagroups":
        if(request.method == "GET"):
            get_data = request.GET
            res = get_data_groups()
            return JsonResponse(res, safe=False)
        else:
            return JsonResponse("Form Data Missing or Invalid Request", safe=False)
    elif action == "addnewdatagroup":
        if(request.method == "POST"):
            post_data = request.POST
            res = add_data_group(post_data, request.user)
            return JsonResponse(res, safe=False)
        else:
            return JsonResponse("Form Data Missing or Invalid Request", safe=False)
    elif action == "removedatagroup":
        if(request.method == "POST"):
            post_data = request.POST
            res = remove_data_group(
                group_id=post_data['group_id'], user=request.user)
            return JsonResponse(res, safe=False)
        else:
            return JsonResponse("Form Data Missing or Invalid Request", safe=False)
    elif action == "editdatagroup":
        if(request.method == "POST"):
            post_data = request.POST
            res = edit_data_group(
                group_id=post_data['group_id'], key=post_data['key'], new_value=post_data['value'], user=request.user)
            return JsonResponse(res, safe=False)
        else:
            return JsonResponse("Form Data Missing or Invalid Request", safe=False)
    elif action == "getshapefilecoord":
        if(request.method == "GET"):
            get_data = request.GET
            res = shapefile_reader(get_data['shapeId'])
            return JsonResponse(res, safe=False)
        else:
            return JsonResponse("Form Data Missing or Invalid Request", safe=False)
    elif action == "getuploadedshapefiles":
        if(request.method == "GET"):
            res = getuploadedshapefiles()
            return JsonResponse(res, safe=False)
        else:
            return JsonResponse("Form Data Missing or Invalid Request", safe=False)
    elif action == "addnewshape":
        if(request.method == "POST"):
            post_data = request.POST
            res = create_new_shape(post_data)
            return JsonResponse(res, safe=False)
        else:
            return JsonResponse("Form Data Missing or Invalid Request", safe=False)
    elif action == "getshapes":
        if(request.method == "GET"):
            res = get_shapes()
            return JsonResponse(res, safe=False)
        else:
            return JsonResponse("Form Data Missing or Invalid Request", safe=False)
    elif action == "getexcelfiles":
        if(request.method == "GET"):
            res = get_excel_files()
            return JsonResponse(res, safe=False)
        else:
            return JsonResponse("Form Data Missing or Invalid Request", safe=False)
    elif action == "getuploads":
        if(request.method == "GET"):
            res = get_uploaded_files()
            return JsonResponse(res, safe=False)
        else:
            return JsonResponse("Form Data Missing or Invalid Request", safe=False)
    elif action == "removeupload":
        if(request.method == "POST"):
            file_id = request.POST['id']
            res = remove_uploaded_file(file_id)
            return JsonResponse(res, safe=False)
        else:
            return JsonResponse("Form Data Missing or Invalid Request", safe=False)
    else:
        return JsonResponse("Invalid Action", safe=False)


def pageNotFound(request):
    return render(request, 'portal/404.html', {'url': request.path_info})

opengisproj/portal/templates/portal/base.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <title>{% block title %} {% endblock %}</title>
        <meta name="viewport" content="width=device-width,initial-scale=1.0" />
        <link rel="stylesheet" href="{% static 'portal/css/bootstrap.min.css' %}"/>
        <link rel="stylesheet" href="{% static 'portal/css/main.css' %}" />
        {% block css %}
        {% endblock %}
        </head>
    <body style="background-image: url('{% static '/portal/images/background.gif' %}');">
        {% include 'portal/partials/menu.html' %}
        <section id="content">
            <div class="container-fluid">
                {% block content %}
                    This is browse view. Edit me in /portal/templates/browse.html
                {% endblock %}
            </div>
        </section>
        <script src="{% static 'portal/js/jquery.min.js' %}"></script>
        <script src="{% static 'portal/js/bootstrap.min.js' %}"></script>
        <script src="{% static 'portal/js/notify.min.js' %}"></script>
        <script src="{% static 'portal/js/functions.js' %}"></script>
        <script>
            //GLobal CSRF Access Token
            var csrftoken = "{{ csrf_token }}";
            var gisMetaFields, gisData, gisGroups;
            var gis_data_stored = false, gis_meta_fields_stored = false, gis_groups_stored = false;
            getMetaFields(storeMetaFields);
            getGisData(storeGisData);
            getGisGroups(storeGisGroups);
        </script>
        {% block js %}
        {% endblock %}

    </body>
</html>

opengisproj/portal/templates/portal/importView.html
{% extends 'portal/base.html' %}
{% load static %}

{% block title %}Import{% endblock %}

{% block css %}
    <link rel="stylesheet" href="{% static 'portal/css/bootstrap-table.min.css' %}" />
    <style>
        #gisImportTable{
            border: 1px solid #ddd;
            border-radius: 8px;
            padding-top: 20px;
        }
        #gisImportTable th{
            font-weight: bold;
            border: 1px solid #ddd;
            padding: 8px;
        }
        #gisImportTable tr{
            margin: 5px;
            padding: 8px;
        }
        #gisImportTable th:hover, tr:hover {
            background-color: #f5f5f5;
        }
        #gisImportTable td{
            padding: 8px;
            border: 1px solid #ddd;
        }
        #submitImporterDataBtn {
            margin: 10px;
        }
    </style>
{% endblock %}

{% block content %}
    <div class="container">
        <h3>Upload New File</h3>
        {% include 'portal/partials/file-uploader.html' %}
    </div>
    <div class="container">
        <h3>Read Existing file</h3>
        <div class="from-group">
            <label for="excelSheetSelector">Select a excel file</label>
            <select id="excelSheetSelector" class="form-control" required>
                <option></option>
            </select>
        </div>
        <div class="form-group">
            <label for="importDataGroupSelector">Select a Data Group</label>
            <select id="importDataGroupSelector" class="form-control" required>
                <option></option>
            </select>
        </div>
        <div class="form-group">
            <button class="btn btn-md btn-primary" id="readExcelFileBtn">Read File</button>
        </div>
    </div>
   <div class="row width-inherit hidden" id="mapGisParam">
        <div class="row">
            <div class="col-xs-12">
                <h3 class="text-center">Map GIS Parameters</h3>
            </div>
            <div class="container">
                <div class="col-xs-12">
                    <form id="addNewImportCheckForm">
                        <div class="form-error text-center text-danger"></div>
                        {% csrf_token %}
                        <div class="form-group Check-group"></div>
                        <button type="submit" class="btn btn-primary center-block" id="addNewCheckBtn">Confirm Parameter Check</button>
                    </form> 
                </div>
            </div>
        </div>
   </div>
    <section class="hidden" id="importTable">
        <div class="row">
            <div class="container">
                <h3 class="text-center loading-text">Data that will be stored</h3>
                <table id="gisImportTable"></table>
            </div>
        </div>
        <div class="row">
            <div class="container">
                <h3 class="text-center loading-text">Data that will not be stored</h3>
                <table id="gisImportTableRejected"></table>
            </div>
        </div>
        <button type="submit" class="btn btn-large btn-primay center-block" id="submitImporterDataBtn">Start Import</button>
        <div class="progress" id="importProgress">
            <div class="progress-bar" role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="0" style="width:0%"></div>
        </div>
    </section>
{% endblock %}

{% block js %}
    <script src="{% static 'portal/js/bootstrap-table.min.js' %}"></script>
    <script>
        $(document).ready(function(e){
            var form = $("#addNewImportCheckForm");
            var apiURI = '/portal/ajax/';
            var submitBtn = $("#addNewCheckBtn");
            var tableError = $(".table-error");
            var excelFields = [];
            var CheckGroup = $(".Check-group");
            var is_excel_field_loaded = false;
            var excelSheetSelector = $("#excelSheetSelector");
            var readExcelFileBtn = $("#readExcelFileBtn");
            var importDataGroupSelector = $("#importDataGroupSelector");
            function init(){
                $("#id_file_meta").val("excel_file");
                $("#id_file_meta").keydown(function(e){
                    e.preventDefault();
                });
                loadDataGroupSelector(importDataGroupSelector);
                loadExcelFiles(excelSheetSelector);
            }
            readExcelFileBtn.click(function(e){
                e.preventDefault();
                if(excelSheetSelector.val() == ""){
                    excelSheetSelector.tooltip({
                        title: "Please select a file",
                        trigger: "manual",
                        placement: "bottom",
                    });
                    excelSheetSelector.tooltip("show");
                    return false;
                }{
                    excelSheetSelector.tooltip("hide");
                }
                if(importDataGroupSelector.val() == ""){
                    importDataGroupSelector.tooltip({
                        title: "Please select a file",
                        trigger: "manual",
                        placement: "bottom",
                    });
                    importDataGroupSelector.tooltip("show");
                    return false;
                }else{
                    importDataGroupSelector.tooltip("hide");
                }
                excelSheetSelector.attr("disabled","disabled");
                importDataGroupSelector.attr("disabled","disabled");
                $(this).attr("disabled","disabled");
                $(this).html("Processing");
                importgisdata(excelSheetSelector.val(), excelField_generate);
                key_name_generate();
            });
            function excelField_generate(excel_data){
                excelFields = excel_data;
                is_excel_field_loaded = true;
            }
            function key_name_generate(){
                var timer = setInterval(function(){
                    if(is_excel_field_loaded == true && gis_meta_fields_stored == true){
                        clearInterval(timer);
                        filtered_fields = filterGisParametersByGroup(importDataGroupSelector.val());
                        var html;
                        for (var x in filtered_fields){
                            html = '<label for="key_name">'+filtered_fields[x].label+' (required)</label>';
                            html += '<select class="form-control keyMapping" name="'+filtered_fields[x].key_name+'" id="'+filtered_fields[x].key_name+'" class="check_name" data-db-key="'+filtered_fields[x].key_name+'" required>';
                            for (var y in excelFields){
                                html += '<option value="'+excelFields[y]+'">'+excelFields[y]+'</option>';
                            }
                            html += '</select>';
                            CheckGroup.append(html);
                        }
                        $("#mapGisParam").removeClass("hidden");
                        readExcelFileBtn.fadeOut();
                    }
                }, 200);   
            }
            submitBtn.click(function(e){
                e.preventDefault();
                var mapping = [];
                CheckGroup.find(".keyMapping").each(function(e){
                    $(this).attr("disabled","disabled");
                    var obj = {};
                    obj["db_key"] = $(this).attr("data-db-key");
                    obj["excel_key"] = $(this).val();
                    mapping.push(obj);
                });
                var file_id = excelSheetSelector.val();
                var data_group = importDataGroupSelector.val();
                submitBtn.attr("disabled","disabled");
                submitBtn.html("Processing");
                getExcelDataFromMapping(file_id, data_group, mapping, readExcelData);
            });
            function readExcelData(data){
                if(data.status!=undefined && data.status == "error"){
                    showNotification("Error Occured: "+data.msg, "error");
                    return false;
                }
                $.each(data.approved, function(i,v){
                    var html = "<tr>";
                    if (i==0){
                        html += '<th class="col-sm-1">Sl. No.</th>';
                    }
                    else{
                        html += '<td class="col-sm-1">'+i+'</td>';
                    }
                    $.each(v, function(key,value){
                        if (i==0){
                            html += '<th class="col-sm-2">'+key+'</th>';
                        }
                        else{
                        html += '<td class="col-sm-2">'+value+'</td>';
                        }
                    });
                    html += '</tr>';
                    $("#gisImportTable").append(html);
                });
                $.each(data.rejected, function(i,v){
                    var html = "<tr>";
                    if (i==0){
                        html += '<th class="col-sm-1">Sl. No.</th>';
                    }
                    else{
                        html += '<td class="col-sm-1">'+i+'</td>';
                    }
                    $.each(v, function(key,value){
                        if (i==0){
                            html += '<th class="col-sm-2">'+key+'</th>';
                        }
                        else{
                        html += '<td class="col-sm-2">'+value+'</td>';
                        }
                    });
                    html += '</tr>';
                    $("#gisImportTableRejected").append(html);
                    submitBtn.fadeOut();
                    $("#importTable").removeClass("hidden");
                });
                $("#submitImporterDataBtn").click(function(e){
                    e.preventDefault();
                    $(this).fadeOut();
                    $("#importProgress").removeClass("hidden");
                    var total = data.approved.length;
                    var counter = 0;
                    submitImporterData(data.approved, importDataGroupSelector.val(), updateProgress);
                    function updateProgress(){
                        counter++;
                        var progress = counter*100/total;
                        $("#importProgress .progress-bar").css('width',progress+"%");
                        if(counter == total){
                            setTimeout(function(){
                                alert("Imported Successfully!");
                                location.reload();
                            },500);
                        }
                    }
                });        
            }
                init();
        });
    </script>
{% endblock %}

opengisproj/portal/templates/portal/index.html
{% extends 'portal/base.html' %}
{% load static %}
{% block title %}Home{% endblock %}
{% block css %}
<style>
    h2{
        font-weight: 600;
    }
    h3{
        font-weight: 600;
        border-bottom: 2px solid #333;
        padding-bottom: 20px;
    }
    .container a{
        color: inherit!important;
    }
    .container  a:hover > .card{
        -webkit-box-shadow: 0px 0px 24px 1px rgba(0,0,0,0.75);
        -moz-box-shadow: 0px 0px 24px 1px rgba(0,0,0,0.75);
        box-shadow: 0px 0px 24px 1px rgba(0,0,0,0.75);
    }
    .card{
        -webkit-box-shadow: 0px 0px 25px -5px rgba(0,0,0,0.75);
        -moz-box-shadow: 0px 0px 25px -5px rgba(0,0,0,0.75);
        box-shadow: 0px 0px 25px -5px rgba(0,0,0,0.75);
        padding:0!important;
        position:relative;
        margin:10px;
        display:-webkit-box;
        display:-webkit-flex;
        display:-ms-flexbox;
        display:flex;
        -webkit-box-orient:vertical;
        -webkit-box-direction:normal;
        -webkit-flex-direction:column;
        -ms-flex-direction:column;
        flex-direction:column;
        background-color:#fff;
        border:1px solid rgba(0,0,0,.125);
        border-radius:.25rem
    }
    .card-title{
        margin-bottom:.75rem;
    }
    .card-subtitle{
        margin-top:-.375rem;
        margin-bottom:0
    }
    .card-text:last-child{
        margin-bottom:0;
    }
    .card-block{
        -webkit-box-flex:1;
        -webkit-flex:1 1 auto;
        -ms-flex:1 1 auto;
        flex:1 1 auto;
        padding:1.25rem
    }
    .card-title{
        margin-bottom:.75rem
    }
    .card-subtitle{
        margin-top:-.375rem;
        margin-bottom:0
    }
    .card-title{
        margin-bottom:.75rem;
        font-size:3rem;
    }
</style>
{% endblock %}

{% block content %}
    <div class="container">
        <br>
        <h2 class="text-right">Welcome, {{ request.user.username }}</h2>
        <h3 class="text-right">This is your dashboard! You can preform actions suggested below</h3>
        <div class="col-xs-12">
            <div class="col-xs-1"></div>
            <a href="{% url 'portal:browse-data' %}">
                <div class="col-xs-3 card" style="width: 30rem;">
                    <img class="card-img-top" src="{% static '/portal/images/database.png' %}" width="298" height="180" alt="Card image cap" />
                    <div class="card-block">
                        <h4 class="card-title">Browse Data</h4>
                        <p class="card-text">Read the database.<br>Edit the data & table.</p>
                    </div>
                </div>
            </a>
            <a href="{% url 'portal:reports' %}">
                <div class="col-xs-3 card" style="width: 30rem;">
                    <img class="card-img-top" src="{% static '/portal/images/report.jpg' %}" width="298" height="180" alt="Card image cap" />
                    <div class="card-block">
                        <h4 class="card-title">Reports</h4>
                        <p class="card-text">Filter data for your purpose.<br>Read the data points on map.</p>
                    </div>
                </div>
            </a>
        </div>
    </div>
{% endblock %}

{% block js %}
{% endblock %}