opengisproj/accounts/urls.py
""" accounts URL Configuration """

from django.conf.urls import url
from django.contrib.auth.views import login, logout
from django.views.generic import RedirectView
from .forms import LoginForm


urlpatterns = [
    url(r'^logout/?$', logout, {'next_page': '/portal'}, name="logout"),
    url(r'^login/?$', login, {'template_name': 'accounts/login.html', 'authentication_form': LoginForm, 'redirect_authenticated_user':True}, name='login'),
    url(r'', RedirectView.as_view(url="/account/login", permanent=False)),
]

opengisproj/opengisproj/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic import RedirectView

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^portal/', include('portal.urls', namespace='portal')),
    url(r'^account/', include('accounts.urls', namespace='accounts')),
    url(r'', RedirectView.as_view(url="/portal/home/", permanent=True)),
]

opengisproj/portal/urls.py
from django.conf.urls import url
from django.views.generic import RedirectView

from . import views

urlpatterns = [
    url(r'^home/?$', views.home, name='home'),
    url(r'^add/?$', views.add, name='add-data'),
    url(r'^browse/?$', views.browse, name='browse-data'),
    url(r'^parameters/?$', views.addParam, name='parameters'),
    url(r'^datagroups/?$', views.dataGroups, name='datagroups'),
    url(r'^reports/?$', views.reports, name='reports'),
    url(r'^shapefiles/?$', views.shapefilesManager, name='shapefiles'),
    url(r'^importer/?$', views.importView, name='importer'),
    url(r'^ajax/(?P<action>[a-zA-Z]*)/?$', views.processAjax, name='ajax'),
    url(r'^fileupload/?$', views.fileupload, name='upload-manager'),
    url(r'^/?$', RedirectView.as_view(url='/portal/home')),
    url(r'', views.pageNotFound, name='404')
]

opengisproj/portal/models.py
from django.db import models
from django.contrib.auth.models import User
from datetime import datetime

# Create your models here.

class data_groups(models.Model):
    name = models.CharField(max_length=100)
    is_removable = models.BooleanField(default=True)
    class Meta:
        db_table = "data_groups"

class gis_data(models.Model):
    created_on = models.DateTimeField(default=datetime.now)
    created_by = models.ForeignKey(User)
    data_group = models.ForeignKey(data_groups)

    class Meta:
        db_table = "gis_data"

class gis_data_meta(models.Model):
    key = models.CharField(max_length=100)
    value = models.TextField()
    data = models.ForeignKey(gis_data,on_delete=models.CASCADE)   

    class Meta:
        db_table = "gis_data_meta"

class options(models.Model):
    option_name = models.CharField(max_length=100)
    value = models.TextField()
    is_removable = models.BooleanField(default=False)
    data_group = models.ForeignKey(data_groups, null=True)

    class Meta:
        db_table = "options"

class uploads(models.Model):
    file_name = models.CharField(max_length=256)
    description = models.TextField(blank=True)
    file_ref = models.FileField(upload_to='uploads/%Y/%m/%d')
    uploaded_at = models.DateTimeField(auto_now_add=True)
    file_meta = models.CharField(max_length=150)
    class Meta:
        db_table = "uploads"

class shapefiles(models.Model):
    shape_name = models.CharField(max_length=256)
    shp_file = models.ForeignKey(uploads, related_name='shp_file', on_delete=models.CASCADE)
    dbf_file = models.ForeignKey(uploads, related_name='dbf_file', on_delete=models.CASCADE)
    shx_file = models.ForeignKey(uploads, related_name='shx_file',on_delete=models.CASCADE)

    class Meta:
        db_table = "shapefiles"

opengisproj/portal/forms.py
from django import forms
from .models import uploads


class UploadForm(forms.ModelForm):
    class Meta:
        model = uploads
        fields = ('file_name', 'description', 'file_ref', 'file_meta')
        labels = {
            'file_name': "Enter File Name",
            'description': "Enter description",
            'file_ref': "Select a file",
            'file_meta': "Upload Type",
        }
        widgets = {
            'file_name': forms.TextInput(attrs={'class': 'form-control',  'required': True}),
            'description': forms.TextInput(attrs={'class': 'form-control'}),
            'file_ref': forms.FileInput(attrs={'class': 'form-control', 'required': True}),
            'file_meta': forms.TextInput(attrs={'class': 'form-control', 'required': True}),
        }

opengisproj/portal/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse, JsonResponse
from .utils import *
from .forms import UploadForm
# Create your views here.


def home(request):
    if request.user.is_authenticated == False:
        return redirect('/portal/reports')
    elif request.user.is_staff == True:
        f = get_meta_fields()
        return render(request, 'portal/index.html', {'meta_fields': f})


def add(request):
    if request.user.is_authenticated == False:
        return redirect('/account/login?next=/portal/add')
    f = get_meta_fields()
    return render(request, 'portal/add-new.html', {'meta_fields': f})


def browse(request):
    if request.user.is_authenticated == False:
        return redirect('/account/login?next=/portal/browse')
    return render(request, 'portal/browse.html')


def addParam(request):
    if request.user.is_authenticated == False:
        return redirect('/account/login?next=/portal/parameters')
    return render(request, 'portal/add-param.html')


def dataGroups(request):
    if request.user.is_authenticated == False:
        return redirect('/account/login?next=/portal/datagroups')
    return render(request, 'portal/data-groups.html')


def reports(request):
    return render(request, 'portal/reports.html')


def shapefilesManager(request):
    if request.user.is_authenticated == False:
        return redirect('/accounts/login?next=/portal/shapefiles')
    form = UploadForm()
    return render(request, 'portal/shapefiles.html', {'form': form, 'meta': 'shapefile'})


def fileupload(request):
    if request.user.is_authenticated == False:
        return redirect('/accounts/login?next=/portal/shapefiles')
    if request.method == 'POST':
        form = UploadForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            form = UploadForm()
            return render(request, 'portal/upload.html', {'msg': "Successfully Uploaded!", 'form': form})
    else:
        form = UploadForm()
        return render(request, 'portal/upload.html', {'form': form})


def importView(request):
    if request.user.is_authenticated == False:
        return redirect('/account/login?next=/portal/importView')
    form = UploadForm()
    return render(request, 'portal/importView.html', {'form': form})


def processAjax(request, action):
    action_ignore_auth = ['getmetafields', 'getgisdata',
                          'getdatagroups', 'getshapes', 'getshapefilecoord']
    if request.user.is_authenticated == False and action not in action_ignore_auth:
        return JsonResponse("Unauthenticated Request", safe=False)
    if action == 'getmetafields':
        res = get_meta_fields()
        return JsonResponse(res, safe=False, content_type="text/html")
    elif action == "addNewData":
        if request.method == "POST":
            post_data = request.POST
            res = add_new_data(post_data, request.user, ret_json=True)
            return JsonResponse(res, safe=False)
        else:
            return JsonResponse("Form Data Missing or Invalid Request", safe=False)
    elif action == "getgisdata":
        if(request.method == "GET"):
            get_data = request.GET
            res = get_meta()
            return JsonResponse(res, safe=False)
        else:
            return JsonResponse("Form Data Missing or Invalid Request", safe=False)
    elif action == "addnewparam":
        if(request.method == "POST"):
            post_data = request.POST
            res = add_param(post_data, user=request.user)
            return JsonResponse(res, safe=False)
        else:
            return JsonResponse("Form Data Missing or Invalid Request", safe=False)
    elif action == "removeparam":
        if(request.method == "POST"):
            post_data = request.POST
            res = remove_param(
                option_id=post_data['id'], group_id=post_data['data_group'], user=request.user)
            return JsonResponse(res, safe=False)
        else:
            return JsonResponse("Form Data Missing or Invalid Request", safe=False)
    elif action == "importgisdata":
        if(request.method == "POST"):
            post_data = request.POST
            res = import_gis_data(post_data['file_id'])
            return JsonResponse(res, safe=False, content_type="text/html")
        else:
            return JsonResponse("Form Data Missing or Invalid Request", safe=False)
    elif action == "getexceldatafrommapping":
        if(request.method == "POST"):
            post_data = request.POST
            res = get_excel_data_from_mapping(
                post_data['mapping'], post_data['file_id'], post_data['data_group'])
            return JsonResponse(res, safe=False, content_type="text/html")
        else:
            return JsonResponse("Form Data Missing or Invalid Request", safe=False)
    elif action == "removedata":
        if(request.method == "POST"):
            post_data = request.POST
            res = remove_gis_data(data_id=post_data['id'], user=request.user)
            return JsonResponse(res, safe=False)
        else:
            return JsonResponse("Form Data Missing or Invalid Request", safe=False)
    elif action == "editdata":
        if(request.method == "POST"):
            post_data = request.POST
            res = edit_gis_data(
                meta_key=post_data['key'], data_id=post_data['dataId'], new_value=post_data['value'], user=request.user)
            return JsonResponse(res, safe=False)
        else:
            return JsonResponse("Form Data Missing or Invalid Request", safe=False)
    elif action == "editparam":
        if(request.method == "POST"):
            post_data = request.POST
            res = edit_gis_param(
                param_key=post_data['key'], opt_id=post_data['paramId'], new_value=post_data['value'], user=request.user)
            return JsonResponse(res, safe=False)
        else:
            return JsonResponse("Form Data Missing or Invalid Request", safe=False)
    elif action == "getdatagroups":
        if(request.method == "GET"):
            get_data = request.GET
            res = get_data_groups()
            return JsonResponse(res, safe=False)
        else:
            return JsonResponse("Form Data Missing or Invalid Request", safe=False)
    elif action == "addnewdatagroup":
        if(request.method == "POST"):
            post_data = request.POST
            res = add_data_group(post_data, request.user)
            return JsonResponse(res, safe=False)
        else:
            return JsonResponse("Form Data Missing or Invalid Request", safe=False)
    elif action == "removedatagroup":
        if(request.method == "POST"):
            post_data = request.POST
            res = remove_data_group(
                group_id=post_data['group_id'], user=request.user)
            return JsonResponse(res, safe=False)
        else:
            return JsonResponse("Form Data Missing or Invalid Request", safe=False)
    elif action == "editdatagroup":
        if(request.method == "POST"):
            post_data = request.POST
            res = edit_data_group(
                group_id=post_data['group_id'], key=post_data['key'], new_value=post_data['value'], user=request.user)
            return JsonResponse(res, safe=False)
        else:
            return JsonResponse("Form Data Missing or Invalid Request", safe=False)
    elif action == "getshapefilecoord":
        if(request.method == "GET"):
            get_data = request.GET
            res = shapefile_reader(get_data['shapeId'])
            return JsonResponse(res, safe=False)
        else:
            return JsonResponse("Form Data Missing or Invalid Request", safe=False)
    elif action == "getuploadedshapefiles":
        if(request.method == "GET"):
            res = getuploadedshapefiles()
            return JsonResponse(res, safe=False)
        else:
            return JsonResponse("Form Data Missing or Invalid Request", safe=False)
    elif action == "addnewshape":
        if(request.method == "POST"):
            post_data = request.POST
            res = create_new_shape(post_data)
            return JsonResponse(res, safe=False)
        else:
            return JsonResponse("Form Data Missing or Invalid Request", safe=False)
    elif action == "getshapes":
        if(request.method == "GET"):
            res = get_shapes()
            return JsonResponse(res, safe=False)
        else:
            return JsonResponse("Form Data Missing or Invalid Request", safe=False)
    elif action == "getexcelfiles":
        if(request.method == "GET"):
            res = get_excel_files()
            return JsonResponse(res, safe=False)
        else:
            return JsonResponse("Form Data Missing or Invalid Request", safe=False)
    elif action == "getuploads":
        if(request.method == "GET"):
            res = get_uploaded_files()
            return JsonResponse(res, safe=False)
        else:
            return JsonResponse("Form Data Missing or Invalid Request", safe=False)
    elif action == "removeupload":
        if(request.method == "POST"):
            file_id = request.POST['id']
            res = remove_uploaded_file(file_id)
            return JsonResponse(res, safe=False)
        else:
            return JsonResponse("Form Data Missing or Invalid Request", safe=False)
    else:
        return JsonResponse("Invalid Action", safe=False)


def pageNotFound(request):
    return render(request, 'portal/404.html', {'url': request.path_info})

opengisproj/portal/templates/portal/partials/file-uploader.html
<form method="post" enctype="multipart/form-data" action="/portal/fileupload/">
    {% csrf_token %}
    {% for x in form %}
        <div class="form-group">
            <label for="{{ x.id_for_label }}">{{ x.label }}</label>
            {{ x }}
        </div>
    {% endfor %}
    <input type="hidden" name="next" value="{{ next }}">
    <button type="submit" class="btn btn-md btn-primary">Upload</button>
</form>

opengisproj/portal/templates/portal/partials/menu.html
<style>
    .dropdown{
        padding: 20px;
        color:#333;
    }
    .navbar{
        background-color: rgba(255,255,255,0.9);
        z-index: 999;
        box-shadow: 0 0 14px 1px #7b7b7b;;
        height: 64px;
        font-size: 18px;
        margin-bottom: 2px;
    }   
    .navbar-brand{
        margin: 0!important;
        font-size: 1.5em;
    }
    .navbar a{
        padding: 20px!important;
        line-height: 25px!important;
    }
    .dropdown{
        padding: 0;
        margin: 0;
    }
    .dataDropdown-toggle{
        height: 65px;
        padding: 20px!important;
        line-height: 25px!important;
    }
    .listHeader{
        margin: 10px;
    }
    .listElement a{
        padding: 10px!important;
        margin: 0!important;
    }
</style>
<div class="navbar navbar-default">
    <div class="container-fluid">
	    <div class="navbar-header">
	        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#mainNav">
    	        <span class="sr-only">Toggle navigation</span>
	            <span class="icon-bar"></span>
	            <span class="icon-bar"></span>
	            <span class="icon-bar"></span>
	        </button>
            <a class="navbar-brand" href="{% url 'portal:home' %}">Open GIS Project</a>
	    </div>
        <div class="collapse navbar-collapse" id="mainNav">
            <ul class="nav navbar-nav">
                {% if user.is_authenticated == True %}
                <li class="dropdown">
                    <a href="#" id='dataDropdown-toggle' class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Data Management<span class="caret"></span></a>
                    <ul class="dropdown-menu padding-20">
                        <li class="listHeader"><strong>GIS Data</strong></li>
                        <li class="listElement"><a href="{% url 'portal:add-data' %}">Add Data</a></li>
                        <li class="listElement"><a href="{% url 'portal:browse-data' %}">Browse Table</a></li>
                        <li role="separator" class="divider"></li>
                        <li class="listHeader"><strong>GIS Parameters</strong></li>
                        <li class="listElement"><a href="{% url 'portal:parameters' %}">Add/Browse Parameters</a></li>
                        <li role="separator" class="divider"></li>
                        <li class="listHeader"><strong>GIS Data Groups</strong></li>
                        <li class="listElement"><a href="{% url 'portal:datagroups' %}">Add/Browse Data Groups</a></li>
                        <li role="separator" class="divider"></li>
                        <li class="listHeader"><strong>Shapefiles</strong></li>
                        <li class="listElement"><a href="{% url 'portal:shapefiles' %}">Browse/Create Shapes</a></li>
                    </ul>
                </li>
                <li class="dropdown">
                    <a href="#" id='dataDropdown-toggle' class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                        Data Tools<span class="caret"></span>
                    </a>
                    <ul class="dropdown-menu padding-20">
                       <li class="listElement"><a href="{% url 'portal:importer' %}">Import GIS Data</a></li>
                       <li class="listElement"><a href="{% url 'portal:upload-manager' %}">Uploads Manager</a></li>
                    </ul>
                </li>
                {% endif %}
                <li><a href="{% url 'portal:reports' %}">Reports</a></li>
                {% if user.is_authenticated == True %}
                <li><a href="{% url 'accounts:logout' %}">Logout</a></li>
                {% else %}
                <li><a href="{% url 'accounts:login' %}">Login</a></li>
                {% endif %}
            </ul>
        </div>
    </div>
</div>